### ISSUE TITLE
Saving title

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Reports-Front#25]
На странице написания отчета имеется функционал сохранения текста отчета, но не заголовка, что выглядит странно для пользователя. Необходимо сохранять и заголовок тоже.

**Comment by IvLaptev** [comment]
В целом да, наверное стоит сохранять. Странно, что пользователя не смущает то, что заголовок вообще пропадает после отправки отчёта.

**Comment by CAPCHIK** [comment]
Ну этот репорт прилетел от Ярослава Смирнова, когда он первый раз пользовался, и смотрел - что и как. Так что то, что он пропадает еще не успел заметить видно)

**Comment by Eloren1** [comment]
@CAPCHIK то есть название отчета после отправки никому не видно?)

**Comment by IvLaptev** [comment]
Сейчас да
