### ISSUE TITLE
Saved status

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Reports-Front#26]
При написании отчета он сохраняется в localStorage, для возможности писать его несколько дней.

Логично было бы иметь индикатор "Изменения сохранены" или около того, для того чтобы человек мог не боясь закрывать вкладку.

@RTUITLab/designers есть идеи, куда и как это можно встроить?

**Comment by tiger-mul** [comment]
Да, мысль имеется, индикатор добавили учитывая нынешнюю верстку
![IMAGE 2021-05-12 00:41:21](https://user-images.githubusercontent.com/83977474/117888473-cc871c80-b2ba-11eb-851f-81b3ba1f34c4.jpg)

**Comment by CAPCHIK** [comment]
> Да, мысль имеется, индикатор добавили учитывая нынешнюю верстку
> ![IMAGE 2021-05-12 00:41:21](https://user-images.githubusercontent.com/83977474/117888473-cc871c80-b2ba-11eb-851f-81b3ba1f34c4.jpg)

Приложи заодно ссылку на эту верстку, пожалуйста. @RTUITLab/frontend необходимо заняться. @IvLaptev  таска выглядит не сложной, думаю будет логично дать кому-то из нового набора. Ну и заодно можно решить и #25

**Comment by CAPCHIK** [comment]
!

**Comment by CAPCHIK** [comment]
@tiger-mul

**Comment by CAPCHIK** [comment]
@tiger-mul

**Comment by CAPCHIK** [comment]
Привет

**Comment by tiger-mul** [comment]
https://www.figma.com/file/pfVZaHnTgFCnAksmEE2UKG/%D0%9E%D1%82%D1%87%D0%B5%D1%82%D1%8B-%D1%80%D0%B5%D0%BB%D0%B8%D0%B7?node-id=0%3A1
